version: '3'

services:
  build-plex:
    build: build-plex
    image: luzithan/build-plex
    env_file:
    - .env
    volumes:
      - /share/Multimedia/Configurations/Plex:/config

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    expose:
      - "32400"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
#      - "80:80/tcp"
      #- "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    hostname: plex_server
    env_file:
      - /share/Multimedia/Configurations/Plex/plex.env
    environment:
      - VIRTUAL_HOST=plex.${DOMAIN}
      - VIRTUAL_PORT=32400
      - PLEX_UID=${UID}
      - PLEX_GID=${GID}
    volumes:
      - /share/Multimedia/Configurations/Plex:/config
      - /tmp:/transcode
      - /share/Movies:/movies
      - /share/TV:/tv
      - /share/Data:/data:shared
    depends_on:
      - build-plex
      - rc-mount
#  tribler:
#    build: tribler
#    expose:
#      - 8085
#    volumes:
#      - /share/Downloads:/home/tribler/TriblerDownloads
#    environment:
#      - CORE_PROCESS=1
#      - CORE_API_PORT=8085
#     - CORE_BASE_PATH=/home/tribler/tribler
#     - VIRTUAL_HOST=tribler.${DOMAIN}
#     - VIRTUAL_PORT=8085
#   ports:
#     - "8085:8085"
#   network_mode: "host"
  transmission-movies:
    image: dperson/transmission
    expose:
      - 9091
    volumes:
      - /share/Movies:/downloads
      - /share/MoviesWatchDir:/watchdir
    environment:
      - TR_RPC_AUTHENTICATION_REQUIRED=true
      - TR_DOWNLOAD_DIR=/downloads
      - TR_RPC_ENABLED=true
      - TR_PEER_PORT=51411
      - TR_WATCH_DIR=/watchdir
      - TR_WATCH_DIR_ENABLED=true
      - TRUSER=${USERNAME}
      - TRPASSWD=${PASSWORD}
      - USERID=${UID}
      - GROUPID=${GID}
      - VIRTUAL_HOST=transmission-movies.${DOMAIN}
      - VIRTUAL_PORT=9091
    ports:
      - "9091:9091"
      - "51411:51411"
    expose:
      - "9091"

  transmission-tv:
    image: dperson/transmission
    expose:
      - 9092
    volumes:
      - /share/TV:/downloads
      - /share/TVWatchDir:/watchdir
    environment:
      - TR_RPC_AUTHENTICATION_REQUIRED=true
      - TR_DOWNLOAD_DIR=/downloads
      - TR_RPC_ENABLED=true
      - TR_PEER_PORT=51412
      - TR_WATCH_DIR=/watchdir
      - TR_WATCH_DIR_ENABLED=true
      - TRUSER=${TRANSMISSION_USERNAME}
      - TRPASSWD=${TRANSMISSION_PASSWORD}
      - USERID=${UID}
      - GROUPID=${GID}
      - VIRTUAL_HOST=transmission-tv.${DOMAIN}
      - VIRTUAL_PORT=9092
    ports:
      - "9092:9091"
      - "51412:51412"
    expose:
      - "9092"

  transmission-data:
    image: dperson/transmission
    expose:
      - 9093
    volumes:
      - /share/Data:/downloads:shared
      - /share/DataWatchDir:/watchdir:shared
    devices:
      - /dev/fuse
    depends_on:
      - rc-mount
    environment:
      - TR_RPC_AUTHENTICATION_REQUIRED=true
      - TR_DOWNLOAD_DIR=/downloads
      - TR_RPC_ENABLED=true
      - TR_PEER_PORT=51413
      - TR_WATCH_DIR=/watchdir
      - TR_WATCH_DIR_ENABLED=true
      - TR_INCOMPLETE_DIR_ENABLED=true
      - TR_INCOMPLETE_DIR=/downloads/_incomplete
      - TRUSER=${TRANSMISSION_USERNAME}
      - TRPASSWD=${TRANSMISSION_PASSWORD}
      - USERID=${UID}
      - GROUPID=${GID}
      - VIRTUAL_HOST=transmission-data.${DOMAIN}
      - VIRTUAL_PORT=9091
    ports:
      - "9093:9091"
      - "51413:51413"
    expose:
      - "9093"
    depends_on:
      - rc-mount

  jackett:
    image: linuxserver/jackett
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - VIRTUAL_HOST=sonarr.${DOMAIN}
      - VIRTUAL_PORT=8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Multimedia/Configurations/Jackett:/config
    expose:
      - "9117"
    ports:
      - "9117:9117"

  couchpotato:
    image: linuxserver/couchpotato
    hostname: couchpotato
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - /share/Multimedia/Configurations/CouchPotato:/config
      - /share/Movies:/downloads
      - /share/MoviesWatchDir:/watchdir
      - VIRTUAL_HOST=couchpotato.${DOMAIN}
      - VIRTUAL_PORT=5050
    expose:
      - 5050
    ports:
      - "5050:5050"

  sonarr:
    image: linuxserver/sonarr
    hostname: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - VIRTUAL_HOST=sonarr.${DOMAIN}
      - VIRTUAL_PORT=8989
    ports:
      - "8989:8989"
    expose:
      - 8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Multimedia/Configurations/Sonarr:/config
      - /share/TV:/downloads
      - /share/TVWatchDir:/watchdir

  radarr:
    image: linuxserver/radarr
    hostname: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - VIRTUAL_HOST=radarr.${DOMAIN}
      - VIRTUAL_PORT=7878
    ports:
      - "7878:7878"
    expose:
      - 7878
    volumes:
      - /share/Multimedia/Configurations/Radarr:/config
      - /share/TV:/downloads
      - /share/TVWatchDir:/watchdir

  dl-serve:
    image: kyma/docker-nginx
    environment:
      - VIRTUAL_HOST=dl-serve.${DOMAIN}
      - VIRTUAL_PORT=9091
    volumes:
      - /share/TV:/var/www/tv
      - /share/Movies:/var/www/movies
      - /share/Data:/var/www/data
    devices:
      - /dev/fuse
    depends_on:
      - rc-mount
    ports:
      - "8082:80"

  emby:
    image: emby/embyserver
    volumes:
      - /share/Multimedia/Configurations/Emby:/config
      - /share/TV:/mnt/shareTV
      - /share/Movies:/mnt/shareMovies
    ports:
      - "8920:8920"
      - "8096:8096"

  rc-mount:
    image: tynor88/rclone-mount:dev
    security_opt:
      - apparmor:unconfine
    devices:
      - /dev/fuse
    cap_add:
      - sys_admin
    volumes:
      - /share/Data:/data:shared
      - /share/Multimedia/Configurations/rc-mount:/config
    environment:
      - RCLONE_REMOTE_MOUNT=remote:${B2_BUCKET}
      - RCLONE_MOUNT_OPTIONS=--buffer-size 1G --timeout 5s --contimeout 5s --cache-total-chunk-size 2G -v --vfs-cache-mode writes
      - RCLONE_CONFIG_REMOTE_TYPE=b2
      - RCLONE_CONFIG_REMOTE_ACCOUNT=${B2_ACCOUNT}
      - RCLONE_CONFIG_REMOTE_KEY=${B2_KEY}
      - MOUNT_UID=1000
      - MOUNT_GID=1000
      - PUID=${UID}
      - PGID=${GID}
