version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    expose:
      - "32400"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
#      - "80:80/tcp"
      #- "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    hostname: plex_server
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP}
      - VIRTUAL_HOST=plex.${DOMAIN}
      - VIRTUAL_PORT=32400
    volumes:
      - /share/Multimedia/Configurations/Plex:/config
      - /tmp:/transcode
      - /share/Download:/data
    volumes:
      - dl-data-movies:/movies
      - dl-data-tv:/tv
    networks:
      - proxy
 # plex-setup:
  #  build: plex-setup
   # environment:
    #  - PLEX_SERVER_HOSTNAME=http://plex
     # - PLEX_AUTH=${PLEX_AUTH}
    #depends_on:
     # plex:
      #  condition: service_healthy
  transmission-movies:
    image: dperson/transmission
    expose:
      - 9091
    volumes:
      - dl-data-movies:/downloads
    environment:
      - TR_RPC_AUTHENTICATION_REQUIRED=true
      - TR_DOWNLOAD_DIR=/downloads
      - TR_RPC_ENABLED=true
      - TR_PEER_PORT=51411
      - TRUSER=${TRANSMISSION_USERNAME}
      - TRPASSWD=${TRANSMISSION_PASSWORD}
      - USERID=0
      - GROUPID=0
      - VIRTUAL_HOST=transmission-movies.${DOMAIN}
      - VIRTUAL_PORT=9091
    ports:
      - "9091:9091"
      - "51411:51411"
    expose:
      - "9091"
    networks:
      - proxy
  transmission-tv:
    image: dperson/transmission
    expose:
      - 9092
    volumes:
      - dl-data-tv:/downloads
    environment:
      - TR_RPC_AUTHENTICATION_REQUIRED=true
      - TR_DOWNLOAD_DIR=/downloads
      - TR_RPC_ENABLED=true
      - TR_PEER_PORT=51412
      - TRUSER=${TRANSMISSION_USERNAME}
      - TRPASSWD=${TRANSMISSION_PASSWORD}
      - USERID=0
      - GROUPID=0
      - VIRTUAL_HOST=transmission-tv.${DOMAIN}
      - VIRTUAL_PORT=9092
    ports:
      - "9092:9091"
      - "51412:51412"
    expose:
      - "9092"
    networks:
      - proxy
  parser:
    build: parser
    hostname: parser
    environment:
      - PARSER_PORT=8081
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - proxy
  dl-serve:
    image: kyma/docker-nginx
    volumes:
      - dl-data-tv:/var/www/tv
      - dl-data-movies:/var/www/movies
    ports:
      - "8080:80"


volumes:
  dl-data-movies:
    driver: local
    driver_opts:
      type: none
      device: /share/Movies
      o: bind
  dl-data-tv:
    driver: local
    driver_opts:
      type: none
      device: /share/TV
      o: bind

networks:
  proxy:
    external:
      name: nginx-proxy