version: '2.1'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      #- "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    hostname: plex_server
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP}
    volumes:
      - /share/Multimedia/Configurations/Plex:/config
      - /tmp:/transcode
      - /share/Download:/data
    volumes_from:
    - torrent-mount-movies:ro
    - torrent-mount-tv:ro
  plex-setup:
    build: plex-setup
    environment:
      - PLEX_SERVER_HOSTNAME=http://plex
      - PLEX_AUTH=${PLEX_AUTH}
    depends_on:
      plex:
        condition: service_healthy
  transmission:
    container_name: transmission
    image: dperson/transmission
    volumes:
      - /share/Multimedia/Configurations/Transmission:/var/lib/transmission-daemon/info
      - /share/Download:/var/lib/transmission-daemon/downloads
      - /share/Movies:/movies
      - /share/TVShows:/tv
      - /share/Watch:/watch
    environment:
      - TR_WATCH_DIR_ENABLED=true
      - TR_WATCH_DIR=/watch
      - TR_RPC_AUTHENTICATION_REQUIRED=true
      - TR_RPC_ENABLED=true
      - TRUSER=${TRANSMISSION_USERNAME}
      - TRPASSWD=${TRANSMISSION_PASSWORD}
      - USERID=0
      - GROUPID=0
    ports:
      - "9091:9091"
      - "51412:51413"
  torrent-mount-tv:
    build: torrent-mount
    volumes:
      - /share/TVShows:/tv
    ports:
      - "8082:8082"
  torrent-mount-movies:
    build: torrent-mount
    volumes:
      - /share/Movies:/movies
    ports:
      - "8083:8083"
  parser:
    build: parser
    hostname: parser
    environment:
      - PARSER_PORT=8081
    ports:
      - "8081:8081"

volumes:
  data:
